language: minimal 

services: docker

before_install:
- docker pull tonyodell/rakudo-nightly:latest

script:
- docker run
  -v $(pwd):/tmp/test:rw
  -v $(pwd)/../.zef:/tmp/.zef:rw
  -w /tmp/test
  --privileged
  tonyodell/rakudo-nightly:latest
  bash -c 'apt update; apt install ca-certificates; curl -v -o /tmp/.zef/store/cpan1.json https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json; zef install -v --config-path=/tmp/test/.travis.json --deps-only . && zef test --config-path=/tmp/test/.travis.json .'
