language: minimal 

services: docker

before_install:
- docker pull tonyodell/rakudo-nightly:latest

script:
- docker run
  -v $(pwd):/tmp/test:rw
  -w /tmp/test
  --privileged
  tonyodell/rakudo-nightly:latest
  bash -c 'zef install -v --config-path=/tmp/test/.travis.json --deps-only . && zef test --config-path=/tmp/test/.travis.json .'
