language: minimal 

services: docker

addons:
  apt:
    packages:
      

before_install:
- docker pull tonyodell/rakudo-nightly:latest

script:
- curl https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
- docker run
  -v $(pwd):/tmp/test:rw
  -w /tmp/test
  --privileged
  tonyodell/rakudo-nightly:latest
  bash -c 'zef update && zef install -v --deps-only . && zef test .'
