language: minimal 

services: docker

before_install:
- docker pull tonyodell/rakudo-nightly:latest

script:
- docker run
  -v $(pwd):/tmp/test:rw
  -w $(pwd)
  tonyodell/rakudo-nightly:latest
  bash -c 'cd /tmp/test; zef install -v --deps-only . && zef test .'
