language: minimal 

services: docker

before_install:
- docker pull tonyodell/rakudo-nightly:latest

script:
- docker run -v $(pwd):/tmp/test:rw tonyodell/rakudo-nightly:latest eval 'cd /tmp/test && zef install --deps-only . && zef test .'
