language: minimal 

services: docker

before_install:
- docker pull tonyodell/rakudo-nightly:latest

script:
- docker run
  -v $(pwd):/tmp/test:rw
  -v $(pwd)/../.zef:/tmp/.zef:rw
  -w /tmp/test
  --privileged
  tonyodell/rakudo-nightly:latest
  bash -c 'apt update; apt install -y ca-certificates; zef install -v --deps-only . && zef test .'
